//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: game.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Game_GameServiceClient`, then call methods of this protocol to make API calls.
internal protocol Game_GameServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Game_GameServiceClientInterceptorFactoryProtocol? { get }

  func connect(
    _ request: Game_User,
    callOptions: CallOptions?
  ) -> UnaryCall<Game_User, Game_GameState>

  func sendMove(
    _ request: Game_Move,
    callOptions: CallOptions?
  ) -> UnaryCall<Game_Move, Game_Move>

  func gameStream(
    _ request: Game_Empty,
    callOptions: CallOptions?,
    handler: @escaping (Game_Move) -> Void
  ) -> ServerStreamingCall<Game_Empty, Game_Move>
}

extension Game_GameServiceClientProtocol {
  internal var serviceName: String {
    return "game.GameService"
  }

  /// Unary call to Connect
  ///
  /// - Parameters:
  ///   - request: Request to send to Connect.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func connect(
    _ request: Game_User,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Game_User, Game_GameState> {
    return self.makeUnaryCall(
      path: Game_GameServiceClientMetadata.Methods.connect.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }

  /// Unary call to SendMove
  ///
  /// - Parameters:
  ///   - request: Request to send to SendMove.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sendMove(
    _ request: Game_Move,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Game_Move, Game_Move> {
    return self.makeUnaryCall(
      path: Game_GameServiceClientMetadata.Methods.sendMove.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendMoveInterceptors() ?? []
    )
  }

  /// Server streaming call to GameStream
  ///
  /// - Parameters:
  ///   - request: Request to send to GameStream.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func gameStream(
    _ request: Game_Empty,
    callOptions: CallOptions? = nil,
    handler: @escaping (Game_Move) -> Void
  ) -> ServerStreamingCall<Game_Empty, Game_Move> {
    return self.makeServerStreamingCall(
      path: Game_GameServiceClientMetadata.Methods.gameStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGameStreamInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Game_GameServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Game_GameServiceNIOClient")
internal final class Game_GameServiceClient: Game_GameServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Game_GameServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Game_GameServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the game.GameService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Game_GameServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Game_GameServiceNIOClient: Game_GameServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Game_GameServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the game.GameService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Game_GameServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Game_GameServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Game_GameServiceClientInterceptorFactoryProtocol? { get }

  func makeConnectCall(
    _ request: Game_User,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Game_User, Game_GameState>

  func makeSendMoveCall(
    _ request: Game_Move,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Game_Move, Game_Move>

  func makeGameStreamCall(
    _ request: Game_Empty,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Game_Empty, Game_Move>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Game_GameServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Game_GameServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Game_GameServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeConnectCall(
    _ request: Game_User,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Game_User, Game_GameState> {
    return self.makeAsyncUnaryCall(
      path: Game_GameServiceClientMetadata.Methods.connect.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }

  internal func makeSendMoveCall(
    _ request: Game_Move,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Game_Move, Game_Move> {
    return self.makeAsyncUnaryCall(
      path: Game_GameServiceClientMetadata.Methods.sendMove.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendMoveInterceptors() ?? []
    )
  }

  internal func makeGameStreamCall(
    _ request: Game_Empty,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Game_Empty, Game_Move> {
    return self.makeAsyncServerStreamingCall(
      path: Game_GameServiceClientMetadata.Methods.gameStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGameStreamInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Game_GameServiceAsyncClientProtocol {
  internal func connect(
    _ request: Game_User,
    callOptions: CallOptions? = nil
  ) async throws -> Game_GameState {
    return try await self.performAsyncUnaryCall(
      path: Game_GameServiceClientMetadata.Methods.connect.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeConnectInterceptors() ?? []
    )
  }

  internal func sendMove(
    _ request: Game_Move,
    callOptions: CallOptions? = nil
  ) async throws -> Game_Move {
    return try await self.performAsyncUnaryCall(
      path: Game_GameServiceClientMetadata.Methods.sendMove.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendMoveInterceptors() ?? []
    )
  }

  internal func gameStream(
    _ request: Game_Empty,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Game_Move> {
    return self.performAsyncServerStreamingCall(
      path: Game_GameServiceClientMetadata.Methods.gameStream.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGameStreamInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Game_GameServiceAsyncClient: Game_GameServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Game_GameServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Game_GameServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Game_GameServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'connect'.
  func makeConnectInterceptors() -> [ClientInterceptor<Game_User, Game_GameState>]

  /// - Returns: Interceptors to use when invoking 'sendMove'.
  func makeSendMoveInterceptors() -> [ClientInterceptor<Game_Move, Game_Move>]

  /// - Returns: Interceptors to use when invoking 'gameStream'.
  func makeGameStreamInterceptors() -> [ClientInterceptor<Game_Empty, Game_Move>]
}

internal enum Game_GameServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "GameService",
    fullName: "game.GameService",
    methods: [
      Game_GameServiceClientMetadata.Methods.connect,
      Game_GameServiceClientMetadata.Methods.sendMove,
      Game_GameServiceClientMetadata.Methods.gameStream,
    ]
  )

  internal enum Methods {
    internal static let connect = GRPCMethodDescriptor(
      name: "Connect",
      path: "/game.GameService/Connect",
      type: GRPCCallType.unary
    )

    internal static let sendMove = GRPCMethodDescriptor(
      name: "SendMove",
      path: "/game.GameService/SendMove",
      type: GRPCCallType.unary
    )

    internal static let gameStream = GRPCMethodDescriptor(
      name: "GameStream",
      path: "/game.GameService/GameStream",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Game_GameServiceProvider: CallHandlerProvider {
  var interceptors: Game_GameServiceServerInterceptorFactoryProtocol? { get }

  func connect(request: Game_User, context: StatusOnlyCallContext) -> EventLoopFuture<Game_GameState>

  func sendMove(request: Game_Move, context: StatusOnlyCallContext) -> EventLoopFuture<Game_Move>

  func gameStream(request: Game_Empty, context: StreamingResponseCallContext<Game_Move>) -> EventLoopFuture<GRPCStatus>
}

extension Game_GameServiceProvider {
  internal var serviceName: Substring {
    return Game_GameServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Connect":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Game_User>(),
        responseSerializer: ProtobufSerializer<Game_GameState>(),
        interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
        userFunction: self.connect(request:context:)
      )

    case "SendMove":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Game_Move>(),
        responseSerializer: ProtobufSerializer<Game_Move>(),
        interceptors: self.interceptors?.makeSendMoveInterceptors() ?? [],
        userFunction: self.sendMove(request:context:)
      )

    case "GameStream":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Game_Empty>(),
        responseSerializer: ProtobufSerializer<Game_Move>(),
        interceptors: self.interceptors?.makeGameStreamInterceptors() ?? [],
        userFunction: self.gameStream(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Game_GameServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Game_GameServiceServerInterceptorFactoryProtocol? { get }

  func connect(
    request: Game_User,
    context: GRPCAsyncServerCallContext
  ) async throws -> Game_GameState

  func sendMove(
    request: Game_Move,
    context: GRPCAsyncServerCallContext
  ) async throws -> Game_Move

  func gameStream(
    request: Game_Empty,
    responseStream: GRPCAsyncResponseStreamWriter<Game_Move>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Game_GameServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Game_GameServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Game_GameServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Game_GameServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Connect":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Game_User>(),
        responseSerializer: ProtobufSerializer<Game_GameState>(),
        interceptors: self.interceptors?.makeConnectInterceptors() ?? [],
        wrapping: { try await self.connect(request: $0, context: $1) }
      )

    case "SendMove":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Game_Move>(),
        responseSerializer: ProtobufSerializer<Game_Move>(),
        interceptors: self.interceptors?.makeSendMoveInterceptors() ?? [],
        wrapping: { try await self.sendMove(request: $0, context: $1) }
      )

    case "GameStream":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Game_Empty>(),
        responseSerializer: ProtobufSerializer<Game_Move>(),
        interceptors: self.interceptors?.makeGameStreamInterceptors() ?? [],
        wrapping: { try await self.gameStream(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol Game_GameServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'connect'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeConnectInterceptors() -> [ServerInterceptor<Game_User, Game_GameState>]

  /// - Returns: Interceptors to use when handling 'sendMove'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSendMoveInterceptors() -> [ServerInterceptor<Game_Move, Game_Move>]

  /// - Returns: Interceptors to use when handling 'gameStream'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGameStreamInterceptors() -> [ServerInterceptor<Game_Empty, Game_Move>]
}

internal enum Game_GameServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "GameService",
    fullName: "game.GameService",
    methods: [
      Game_GameServiceServerMetadata.Methods.connect,
      Game_GameServiceServerMetadata.Methods.sendMove,
      Game_GameServiceServerMetadata.Methods.gameStream,
    ]
  )

  internal enum Methods {
    internal static let connect = GRPCMethodDescriptor(
      name: "Connect",
      path: "/game.GameService/Connect",
      type: GRPCCallType.unary
    )

    internal static let sendMove = GRPCMethodDescriptor(
      name: "SendMove",
      path: "/game.GameService/SendMove",
      type: GRPCCallType.unary
    )

    internal static let gameStream = GRPCMethodDescriptor(
      name: "GameStream",
      path: "/game.GameService/GameStream",
      type: GRPCCallType.serverStreaming
    )
  }
}

